project: KaffeeJS
tagline: Vert.x Web Application Framework for CoffeeScript/JavaScript
repo: khoinguyen/vertx-mods-kaffee
repoUrl: https://github.com/khoinguyen/vertx-mods-kaffee
maintainer: khoinguyen
ga: UA-48462762-1
domain: kaffeejs.com